export const FETCH_COURSE_REQUEST = "FETCH_COURSE_REQUEST";
export const FETCH_SEARCH_COURSE_REQUEST = "FETCH_SEARCH_COURSE_REQUEST";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAILURE = "FETCH_COURSE_FAILURE";

export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const EDIT_COURSE_REQUEST = "EDIT_COURSE_REQUEST";
export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const REGISTER_COURSE_REQUEST = "REGISTER_COURSE_REQUEST";
export const CONFIRM_EXIST_COURSE_REQUEST = "CONFIRM_EXIST_COURSE_REQUEST";
export const COURSE_SUCCESS = "COURSE_SUCCESS";
export const COURSE_FAILURE = "COURSE_FAILURE";